import path from 'node:path';
import { randomUUID } from 'node:crypto';
import { type Actor } from '../../../../shared/application/actor';
import { type SystemLogger } from '../../../../shared/application/activity-log.port';
import { type UnitOfWork } from '../../../../shared/application/unit-of-work.port';
import { DomainError } from '../../../../shared/domain/errors';
import { Uuid } from '../../../../shared/domain/identifier';
import { type FileStoragePort, type ImageProcessorPort } from '../../../../shared/application/file-storage.port';
import { DemandAttachment, isAllowedMimeType } from '../../domain/demand-attachment';
import { type DemandActivityLog } from '../demand-activity';
import { type AttachmentRepository } from '../ports/repositories';
import { removeStoredFiles } from '../storage-cleanup';
import { type DemandAccessGuard, type DemandAttachmentDTO } from './demand.use-cases';

export interface IncomingFile {
  originalName: string;
  mimeType: string;
  content: Buffer;
}

/** Extensions that must line up with the declared MIME type. */
const EXTENSION_BY_MIME: Record<string, string[]> = {
  'image/jpeg': ['.jpg', '.jpeg'],
  'image/png': ['.png'],
  'image/webp': ['.webp'],
  'application/pdf': ['.pdf'],
  'text/plain': ['.txt'],
  'text/csv': ['.csv'],
  'application/msword': ['.doc'],
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document': ['.docx'],
  'application/vnd.ms-excel': ['.xls'],
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': ['.xlsx'],
  'application/zip': ['.zip'],
};

function attachmentMetadata(attachment: DemandAttachment) {
  return {
    attachment: {
      uuid: attachment.uuid.toString(),
      name: attachment.originalName,
      mimeType: attachment.mimeType,
      sizeBytes: attachment.sizeBytes,
    },
  };
}

export class UploadAttachments {
  constructor(
    private readonly guard: DemandAccessGuard,
    private readonly attachments: AttachmentRepository,
    private readonly storage: FileStoragePort,
    private readonly images: ImageProcessorPort,
    private readonly uow: UnitOfWork,
    private readonly activity: DemandActivityLog,
  ) {}

  async execute(
    actor: Actor,
    demandUuid: string,
    files: IncomingFile[],
  ): Promise<DemandAttachmentDTO[]> {
    actor.require('DEMAND_UPDATE');
    const demand = await this.guard.loadAccessible(actor, demandUuid);

    if (files.length === 0) {
      throw DomainError.validation('NO_FILES', 'Nenhum arquivo enviado.');
    }
    // Every file is checked before any is stored: one bad file in a batch of five must
    // not leave four blobs behind.
    files.forEach(assertTypeConsistency);

    const stored: { attachment: DemandAttachment; thumbnailKey: string | null }[] = [];

    for (const file of files) {
      // The storage key is generated by the application and carries no user input:
      // the original filename is preserved only as metadata, never as a path segment.
      const extension = EXTENSION_BY_MIME[file.mimeType]?.[0] ?? '';
      const baseKey = `demands/${demand.uuid.toString()}/${randomUUID()}`;
      const storageKey = `${baseKey}${extension}`;

      const upload = await this.storage.upload({
        storageKey,
        contentType: file.mimeType,
        content: file.content,
      });

      let thumbnailKey: string | null = null;
      if (this.images.isSupported(file.mimeType)) {
        try {
          const thumbnail = await this.images.createThumbnail(file.content);
          thumbnailKey = `${baseKey}-thumb.webp`;
          await this.storage.upload({
            storageKey: thumbnailKey,
            contentType: thumbnail.contentType,
            content: thumbnail.content,
          });
        } catch {
          // A corrupt or exotic image must not fail the upload; the card simply falls
          // back to the original file for its preview.
          thumbnailKey = null;
        }
      }

      const attachment = DemandAttachment.create({
        originalName: sanitizeName(file.originalName),
        mimeType: file.mimeType,
        sizeBytes: upload.sizeBytes,
        storageKey: upload.storageKey,
        thumbnailKey,
        createdByUserUuid: actor.userUuid,
      });

      // The aggregate refuses attachments on a demand in production.
      demand.attach(attachment);
      stored.push({ attachment, thumbnailKey });
    }

    // Bytes are written outside the transaction — image processing inside one would
    // hold locks for as long as Sharp takes. Rows and their activity commit together.
    await this.uow.run(async () => {
      for (const { attachment } of stored) {
        await this.attachments.add(demand.uuid, attachment);
      }
      const card = await this.activity.snapshot(demand.uuid);
      for (const { attachment } of stored) {
        await this.activity.record(actor, 'demand.attachment_added', card, {
          metadata: attachmentMetadata(attachment),
        });
      }
    });

    return stored.map(({ attachment, thumbnailKey }) => ({
      uuid: attachment.uuid.toString(),
      originalName: attachment.originalName,
      mimeType: attachment.mimeType,
      sizeBytes: attachment.sizeBytes,
      isImage: attachment.isImage(),
      url: this.storage.resolveUrl(attachment.storageKey),
      thumbnailUrl: thumbnailKey ? this.storage.resolveUrl(thumbnailKey) : null,
    }));
  }
}

export class DeleteAttachment {
  constructor(
    private readonly guard: DemandAccessGuard,
    private readonly attachments: AttachmentRepository,
    private readonly storage: FileStoragePort,
    private readonly uow: UnitOfWork,
    private readonly activity: DemandActivityLog,
    private readonly systemLogger: SystemLogger,
  ) {}

  async execute(actor: Actor, demandUuid: string, attachmentUuid: string): Promise<void> {
    actor.require('DEMAND_UPDATE');
    const demand = await this.guard.loadAccessible(actor, demandUuid);

    if (!Uuid.isValid(attachmentUuid)) {
      throw DomainError.notFound('ATTACHMENT_NOT_FOUND', 'Anexo não encontrado.');
    }
    // The aggregate owns the "does this attachment belong to me" check.
    const removed = demand.removeAttachment(Uuid.create(attachmentUuid));

    const card = await this.uow.run(async () => {
      const snapshot = await this.activity.snapshot(demand.uuid);
      await this.attachments.remove(removed.uuid);
      await this.activity.record(actor, 'demand.attachment_removed', snapshot, {
        metadata: attachmentMetadata(removed),
      });
      return snapshot;
    });

    await removeStoredFiles(
      this.storage,
      this.systemLogger,
      { actor, demand: { uuid: card.uuid, title: card.title } },
      [removed.storageKey, ...(removed.thumbnailKey ? [removed.thumbnailKey] : [])],
    );
  }
}

/**
 * A declared MIME type is client-supplied and trivially forged, so it must agree with
 * the file extension before anything is written. This is the cheap half of the check;
 * the expensive half is that images are re-encoded by Sharp, which fails on anything
 * that is not actually an image.
 */
function assertTypeConsistency(file: IncomingFile): void {
  if (!isAllowedMimeType(file.mimeType)) {
    throw DomainError.validation(
      'UNSUPPORTED_MIME_TYPE',
      `Tipo de arquivo não suportado: ${file.mimeType}.`,
    );
  }
  const extension = path.extname(file.originalName).toLowerCase();
  const allowed = EXTENSION_BY_MIME[file.mimeType] ?? [];
  if (!allowed.includes(extension)) {
    throw DomainError.validation(
      'MIME_EXTENSION_MISMATCH',
      `A extensão "${extension || 'ausente'}" não corresponde ao tipo ${file.mimeType}.`,
    );
  }
}

/**
 * Keeps the display name readable while stripping path separators, Windows-reserved
 * characters and control bytes. This value is metadata only, never a path segment.
 */
function sanitizeName(name: string): string {
  const reserved = new Set(['<', '>', ':', '"', '/', '|', '?', '*', String.fromCharCode(92)]);
  const cleaned = Array.from(path.basename(name))
    .filter((char) => !reserved.has(char) && char.charCodeAt(0) >= 32)
    .join('')
    .trim();
  return cleaned.slice(0, 255) || 'arquivo';
}
